POST http://localhost:8080/test-insertion/save-concurrent-and-atomic-by-transaction-id-two-table/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-concurrent-and-atomic-by-transaction-id-another-table/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-concurrent-and-atomic-by-transaction-id/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-concurrent-and-atomic/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-array-after-insert/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-after-insert/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-by-kproperty/a833fee4-91b9-4804-ad58-c12377b218ef
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-by-transaction-id/98f0cc67-5326-4eeb-9836-eecede946ccd
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-transaction-id/2?countRow=20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-array/4
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-unnest/8
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read/5
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/remove-transaction-id-after-insert/10
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-update-by-session/10
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-by-spring-with-async-and-session/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-by-spring-with-async/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-by-spring-with-async/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-with-async-repository/3
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-binary/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-property/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-binary-and-property/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-file/200?transactionId=c2cfa59d-69cc-43b3-a749-c3c44dd04333
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-binary-file/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-file-and-property/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/copy-by-binary-file-and-property/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert/1
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-prepared-statement/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-prepared-statement-unnest/10
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-prepared-statement/200?orderNumber=NumberForUpdate
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-by-pg-query/200?transactionId=c2cfa59d-69cc-43b3-a749-c3c44dd04323
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-by-pg-query-with-app-loop/200?transactionId=c2cfa59d-69cc-43b3-a749-c3c44dd04323
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-prepared-statement/200?transactionId=c2cfa59d-69cc-43b3-a749-c3c44dd04323
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-by-spring-with-async/200?transactionId=a833fee4-91b9-4804-ad58-c12377b218ef
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update-only-one-field-with-common-condition-after-insert/2000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update-only-one-field-with-common-condition/NumberForUpdate?prop10=UpdProp1
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update/10
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update-prepared-statement/40
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/insert-by-property/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update-by-property/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update-by-property-prepared-statement/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/update-only-one-field-by-property-prepared-statement/1
Content-Type: application/json

###
#POST http://localhost:8080/test-insertion/insert-with-drop-index/200
#Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring/2
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-save-all/40
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-with-manual-persisting/6
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-with-copy/1
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-save-all-with-copy/1
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-with-copy-concurrent/5
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-jdbc-template/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-named-jdbc-template/200
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-by-crud-repository/5
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-update/10
Content-Type: application/json
