ALTER TABLE PAYMENT_DOCUMENT ADD COLUMN transaction_id uuid DEFAULT null;
CREATE TABLE ACTIVE_TRANSACTION
(
    ID bigint NOT NULL DEFAULT nextval('seq_id'),
    transaction_id uuid NOT NULL
);
CREATE INDEX IX_ACTIVE_TRANSACTION_transaction_id on ACTIVE_TRANSACTION (transaction_id);

-- CREATE TABLE ACTIVE_TRANSACTION
-- (
--     ID bigint NOT NULL,
--     transaction_id uuid NOT NULL
-- );
-- ALTER TABLE ACTIVE_TRANSACTION ADD CONSTRAINT PK_ACTIVE_TRANSACTION PRIMARY KEY (ID);
-- CREATE INDEX IX_ACTIVE_TRANSACTION_transaction_id on ACTIVE_TRANSACTION (transaction_id);